## Introdução sobre python


In [2]:
#Declaração de variaveis

#Inteiros
idade = 21
#Float
altura = 1.75
#Strings
nome = 'alvaro'
#Bool 
gosta_do_flamengo = True

In [4]:
# Printando valores:
print(idade)
print(altura)
print(nome)
print(gosta_do_flamengo)

# Lendo valores:
meu_nome = input("Entre com seu nome:")

# '+' concatena duas strings:
print("Olá " + meu_nome)


# Podemos usar 'aspas simples' ou "aspas duplas" para strings:
minha_idade = (input('Entre com sua idade:'))

# Também podemos usar o próprio print para concatenar:
print('Sua idade é', minha_idade)

21
1.75
alvaro
True
Olá 
Sua idade é 


## Operadores aritméticos



In [ ]:
x = float(input('Entre com um número:'))
y = float(input('Entre com outro número:'))

soma = x + y
subtracao = x - y
multiplicacao = x * y
divisao = x / y
potencia = x ** y
resto = x % y
divisao_inteira = x // y

print('Soma:', soma)
print('Subtração:', subtracao)
print('Multiplicação:', multiplicacao)
print('Divisão:', divisao)
print('Potência:', potencia)
print('Resto:', resto)
print('Divisão inteira:', divisao_inteira)



## Operadores lógicos e de comparaçãoo

### Operadores de comparação

Os operadores de comparação permitem verificar igualdades e desigualdades entre valores, sendo possível verificar se tal condição é verdadeira ou falsa. Dentre eles temos:
```python
igual = x == y
diferente = x != y
menor = x < y
maior = x > y
menor_igual = x <= y
maior_igual = x >= y```

### Operadores lógicos

Os operadores lógicos são operadores que recebem `bools` como argumento e retornam um `bool`. Dentre eles podem destacar:
```python
e_logico = x and y
ou_logico = x or y
nao_logico = not x```

In [6]:
x = float(input("Entre com um valor: "))
y = float(input("Entre com outro valor: "))

if x > y:
    print(x, ">", y)
elif x == y and x == 42:
    print("A resposta para a vida, o universo e tudo mais")
elif x < 0 or y < 0:
    print("Algum valor é negativo")
else:
    print("Nenhum bloco acima foi executado")

42.0 > 0.0


In [5]:
x = float(input("Entre com um valor:"))

if 0 < x <= 10:
    print(x, "é maior que 0 e menor ou igual a 10")
elif -100 <= x <= 0:
    print(x, "está entre -100 e 0")
else:
    print(x, "é maior que 10 ou menor que -100")

11.0 é maior que 10 ou menor que -100


## Listas
Podemos crias listas homogeneas(isto é , podem conter qualquer tipo de variável)

In [7]:
lista_1 = ["Multimidia", 100, True]
print(lista_1)

['Multimidia', 100, True]


## Métodos e funções úteis para listas
Funções e metodos uteis para manusear funções

In [8]:
lista_2 = [42, 'Python', 3.1415, lista_1]

#Tamanho de uma lista:
print(len(lista_2))

#Adicionando um novo elemento
lista_2.append(1.90)
lista_2.insert(2,False)

#Acessando valores individuais
print("Elemento na posição 0:", lista_2[0]) # Pega o elemento na posição 0.
print("Último elemento:", lista_2[-1]) # Pega o último elemento.
print("Penúltimo elemento:", lista_2[-2]) # Pega o penúltimo elemento.
print("Elemento na posição 2 e 3:", lista_2[2:4]) # Pega os elementos 2 e 3. Obs.: Primeiro valor incluso e último excluso.

#Reverter lista
lista_2.reverse()
print(lista_2)

#Ordenação
lista3 = [8, 4, 3, 10, -20]
lista3.sort()
print(lista3)

lista3.sort(reverse=True) # Ordena de forma decrescente
print(lista3)

4
Elemento na posição 0: 42
Último elemento: 1.9
Penúltimo elemento: ['Multimidia', 100, True]
Elemento na posição 2 e 3: [False, 3.1415]
[1.9, ['Multimidia', 100, True], 3.1415, False, 'Python', 42]
[-20, 3, 4, 8, 10]
[10, 8, 4, 3, -20]


## Elementos de repetição



While -> Executa comandos dentro do bloco while enquanto a condição é verdadeira


In [9]:
x = 512
while x >1:
    print('x = ', x)
    x = x // 2 # Divisão inteira

x =  512
x =  256
x =  128
x =  64
x =  32
x =  16
x =  8
x =  4
x =  2


For -> permite iterar por valores dentro de uma entrutura


In [10]:
lista2 = [42, "Python", 3.14159]

for valor in lista2:
    print(valor)

42
Python
3.14159


In [11]:
print("[0, 5):")
for i in range(5):
    print(i)

print()
    
print("[2, 8):")
for j in range(2, 8):
    print(j)
    
print()
    
print("[4, 9) com passo 2:")
for k in range(4, 9, 2):
    print(k)

[0, 5):
0
1
2
3
4

[2, 8):
2
3
4
5
6
7

[4, 9) com passo 2:
4
6
8


## Tuplas
Tuplas funcionam como listas homogeneas de tamanho fixo e imutáveis



In [12]:
louis = ('Louis XIV', 'França')
beethoven = ('Beethoven', 'Alemanha')
aristoteles = ('Aristoteles', 'Grécia') 
#Acessando valores
print(louis[0]) # Nome

#Descontrução em tuplas
nome, pais = aristoteles
print(nome, pais)

Louis XIV
Aristoteles Grécia


## Funçõe4s


In [ ]:
def soma(x, y = 5):
    z = x + y
    return z

print(soma(10, 20)) # Passando dois argumentos
print(soma(10)) # Passando apenas o primeiro argumento

30
15


In [14]:
#Função sem retorno
def mostra_paridade(valores):
    for valor in valores:
        if valor % 2 == 0:
            print(valor, "é par")
        else:
            print(valor, "é ímpar")
mostra_paridade(range(0, 10))

0 é par
1 é ímpar
2 é par
3 é ímpar
4 é par
5 é ímpar
6 é par
7 é ímpar
8 é par
9 é ímpar


## Funções anonimas
Chamadas de funções lambdas sao funções que podem ser salvas em variaveis


In [15]:
mostra_passos = lambda nome, idade: nome + " tem " + str(idade) + " anos"
print(mostra_passos("Alvaro", 21))

Alvaro tem 21 anos


In [16]:
pontos = [(2, 5), (-1, 0), (6, 3), (2, -3)]

pontos_crescentes_em_x = sorted(pontos, key=lambda p: p[0])
pontos_decrescentes_em_x = sorted(pontos, key=lambda p: p[0], reverse = True)

print('Ordem crescente: ', pontos_crescentes_em_x)
print('Ordem decrescente: ',pontos_decrescentes_em_x)

Ordem crescente:  [(-1, 0), (2, 5), (2, -3), (6, 3)]
Ordem decrescente:  [(6, 3), (2, 5), (2, -3), (-1, 0)]


In [17]:
from operator import itemgetter

sorted(pontos, key=itemgetter(0))

[(-1, 0), (2, 5), (2, -3), (6, 3)]

## Arrays do Numpy

Arrays do numpy sao  mais eficientes e oferecem mais operações úteis relacionadas a manipulação de vetores e matrizes algébricas

In [18]:
import numpy as np
vetor = np.array([1, 2, 3])


In [20]:
vetor_float = np.array([1.0, 2.0, 3.0])
print(vetor_float)
print(vetor_float.dtype) # Tipo do vetor

vetor_int = np.array([1, 2, 3], dtype = np.int8) # Definindo o tipo do vetor
print(vetor_int)
print(vetor_int.dtype) # Tipo do vetor


[1. 2. 3.]
float64
[1 2 3]
int8


In [21]:
#Matrizes 
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)
print(matriz.shape) # Dimensões da matriz


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## Funções e operações relevantes 

Criação de arrays

In [23]:
print('Array tamanho 2x4 preenchido com 1')
print(np.ones((2, 4))) # Array de 2x4 preenchido com 1
print('Array tamanho 2x4 preenchido com 0')
print(np.zeros((2, 4))) # Array de 2x4 preenchido com 0
print('Array 3x4 com valores aleatorios em [0,10]   ')
np.random.seed(0) # Semente para gerar os mesmos números aleatórios
print(np.random.randint(0, 10, (3, 4))) # Array 3x4 com valores aleatórios em [0,10]
print('Array 3x4 com valores  em [0,1] com passo de 0.1  ')
print(np.arange(0, 1, 0.1)) # Array 3x4 com valores em [0,1] com passo de 0.1

Array tamanho 2x4 preenchido com 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array tamanho 2x4 preenchido com 0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 3x4 com valores aleatorios em [0,10]   
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
Array 3x4 com valores  em [0,1] com passo de 0.1  
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Transposta e concatenação:

In [24]:
matriz_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz_2x3)

print('\nTransposta')
print(matriz_2x3.T) # Transposta da matriz

matriz_2x2 = np.array([[1, 2], [3, 4]])
print(matriz_2x2)

matriz_3x3 = np.array([[6, 7, 8], [9, 10, 11], [12, 13, 14]])
print('\nMatriz 3x3:')
print(matriz_3x3)

print('\nMatriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):')
print(np.concatenate([matriz_2x3, matriz_3x3], axis=0))

print('\nMatriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):')
#Exige que o numero de linhas seja o mesmo nas duas matrizes. com axis =1
print(np.concatenate([matriz_2x3, matriz_2x2], axis=1))

[[1 2 3]
 [4 5 6]]

Transposta
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]]

Matriz 3x3:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 3x3 - Concatenação no eixo das linhas (eixo 0):
[[ 1  2  3]
 [ 4  5  6]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Matriz 2x3 e Matriz 2x2 - Concatenação no eixo das colunas (eixo 1):
[[1 2 3 1 2]
 [4 5 6 3 4]]


## Indexação de matrizes 


In [25]:
matriz_4x3 = np.array([[0,  1,  2],
                       [3,  4,  5],
                       [6,  7,  8],
                       [9, 10, 11]])

print("Linha de índice 0:", matriz_4x3[0]) # linha de índice 0
print("Linha 2 e coluna 1:", matriz_4x3[2, 1]) # linha de índice 2 ([6, 7, 8]) e coluna de índice 1
print("Todas linhas e coluna 1:", matriz_4x3[:, 1]) # todas as linhas e coluna de índice 1
print("Linhas [1, 3) e colunas >= 1:\n", matriz_4x3[1:3, 1:]) # linhas [1, 3), todas as colunas a partir de 1
print(matriz_4x3.dtype)

Linha de índice 0: [0 1 2]
Linha 2 e coluna 1: 7
Todas linhas e coluna 1: [ 1  4  7 10]
Linhas [1, 3) e colunas >= 1:
 [[4 5]
 [7 8]]
int32


## Operações

In [26]:
print('Multiplicação com escalar:')
print(np.ones((2, 3)) * 2)

print('\nSoma com escalar:')
print(np.zeros(6) + 3)

print('\nSoma ponto-a-ponto:')
# Equivalente a [[1, 1], [1, 1]] + [[10, 10], [10, 10]]:
print(np.ones((2, 2)) + 10 * np.ones((2, 2)))

print('\nMultiplicação ponto-a-ponto:')
# Equivalente a [2, 2, 2, 2] * [5, 5, 5, 5]:
print((2 * np.ones(4)) * (5 * np.ones(4)))

print('\nMultiplicação matricial:')
print(
    np.matmul(
        np.array([[1, 2],
                  [3, 4]]),
        np.array([[5, 6],
                  [7, 8]])))

print('\nProduto escalar:')
#Equivalente a 1 * (-1) + 2 * 0 + 3 * 1:
print(np.dot(np.array([1, 2, 3]), np.array([-1, 0, 1])))

Multiplicação com escalar:
[[2. 2. 2.]
 [2. 2. 2.]]

Soma com escalar:
[3. 3. 3. 3. 3. 3.]

Soma ponto-a-ponto:
[[11. 11.]
 [11. 11.]]

Multiplicação ponto-a-ponto:
[10. 10. 10. 10.]

Multiplicação matricial:
[[19 22]
 [43 50]]

Produto escalar:
2


In [32]:
np.random.seed(42)
a = np.random.randint(0,11,size = (8, 8 ,3), dtype = np.int8)
b = np.random.randint(0,11,size = (8,8,3), dtype = np.int8)
print(a)
print(b)
print(a.dtype, b.dtype) # Tipo do vetor

[[[ 6  1  3]
  [10  3  2]
  [ 3  5  5]
  [10  4  3]
  [ 7  4  9]
  [ 7  1  9]
  [ 4  8  6]
  [ 6  0  7]]

 [[ 9  8  2]
  [ 2  2  1]
  [ 7  6  4]
  [ 7  9 10]
  [ 1 10  5]
  [ 1  5  7]
  [ 8  4  5]
  [ 3  2  9]]

 [[ 7  2  4]
  [ 7  4  5]
  [ 2  0  0]
  [ 6  5  6]
  [ 5  5  4]
  [ 0  1  3]
  [ 8  7  9]
  [ 4  8  5]]

 [[10  5  4]
  [ 0  5  6]
  [ 1  9  3]
  [ 0  4  3]
  [ 1  4  9]
  [ 3  0  4]
  [ 3  1  2]
  [ 9  5  5]]

 [[ 0  6  6]
  [ 8  1  2]
  [ 3  8  7]
  [ 5  0 10]
  [10  1  7]
  [ 6 10  4]
  [ 2  9  6]
  [ 9  5  3]]

 [[ 7  2  9]
  [10 10  8]
  [ 9  3  9]
  [ 7  6  0]
  [ 1  4  1]
  [ 7 10  1]
  [ 9  2  2]
  [ 3  7  9]]

 [[ 1  6  4]
  [ 3  3  4]
  [ 5  8  7]
  [ 8  5  7]
  [ 2  4  4]
  [ 5  2  8]
  [ 6  2  8]
  [ 4  8  7]]

 [[ 8  3  3]
  [ 6  8  7]
  [ 0  1  5]
  [ 5  3  3]
  [ 9 10  2]
  [ 8  2  4]
  [ 1  9  3]
  [ 7  8  3]]]
[[[ 1  0  3]
  [ 9  7 10]
  [ 2  8  9]
  [ 6  4  4]
  [10  1  9]
  [ 1  3  5]
  [ 9  8  3]
  [ 5  0 10]]

 [[ 6  5  8]
  [ 9  3  7]
  [ 3  5  8]
  [ 2  

In [ ]:
c= np.mean([a,b], axis = 0) # Axis =0 faz a media ponto a ponto, axis =1 compara dentro de cada array
c # Média entre os dois vetores

array([[[3.5, 0.5, 3. ],
        [9.5, 5. , 6. ],
        [2.5, 6.5, 7. ],
        [8. , 4. , 3.5],
        [8.5, 2.5, 9. ],
        [4. , 2. , 7. ],
        [6.5, 8. , 4.5],
        [5.5, 0. , 8.5]],

       [[7.5, 6.5, 5. ],
        [5.5, 2.5, 4. ],
        [5. , 5.5, 6. ],
        [4.5, 4.5, 5.5],
        [4.5, 9.5, 6.5],
        [0.5, 4.5, 5. ],
        [7.5, 3. , 3. ],
        [4.5, 4.5, 8. ]],

       [[8. , 2.5, 2.5],
        [4. , 3.5, 6. ],
        [3.5, 1.5, 2.5],
        [5.5, 7.5, 5.5],
        [7. , 4.5, 4.5],
        [1.5, 2.5, 2. ],
        [6.5, 4.5, 7. ],
        [4. , 8. , 3.5]],

       [[8. , 6.5, 2.5],
        [4.5, 6. , 7.5],
        [5.5, 7.5, 4.5],
        [1.5, 3.5, 2. ],
        [0.5, 3.5, 4.5],
        [6. , 0. , 6. ],
        [4. , 4. , 2.5],
        [7. , 4. , 4. ]],

       [[4.5, 7.5, 7.5],
        [9. , 2. , 5. ],
        [3. , 7.5, 4. ],
        [6. , 3. , 9. ],
        [6. , 3.5, 4.5],
        [5. , 7.5, 4.5],
        [5. , 6. , 5. ],
        [7.5, 6. 

In [37]:
#Concatenação horizontal (axis = 1) e vertical (axis = 0)
d = np.concatenate([a,b,c], axis = 1)
#Guardar o subarray
subarray = d[1:8,0:3,1]
print(subarray)

[[ 8.  2.  6.]
 [ 2.  4.  0.]
 [ 5.  5.  9.]
 [ 6.  1.  8.]
 [ 2. 10.  3.]
 [ 6.  3.  8.]
 [ 3.  8.  1.]]


In [ ]:
a.shape,b.shape
np.mul(a.shape[2],b.shape[2]) # Multiplicação de matrizes)

AttributeError: module 'numpy' has no attribute 'mul'

In [41]:
mult = np.matmul(a[:,:,0], b[:,:,1])

5. Crie uma função que receba um array bidimensional e retorne uma tupla `(m, p)`, onde `m` é o maior valor e `p` é a posição `(x, y)` no array onde se encontra `m`. Faça uso do `while` ou do `for` vistos acima. Caso tenha mais de uma posição com valor máximo, utilize a posição mais antiga.

In [ ]:
#5. Crie uma função que receba um array bidimensional e retorne uma tupla `(m, p)`, onde `m` é o maior valor e `p` é a posição `(x, y)` no array onde se encontra `m`. Faça uso do `while` ou do `for` vistos acima. Caso tenha mais de uma posição com valor máximo, utilize a posição mais antiga- USANDO NUMPY.
def maior_valor(matriz):
    if matriz.shape != 2:
        raise ValueError("A matriz deve ser bidimensional")

    else
        break
